name: Deploy to EC2

on:
  push:
    branches:
      - main  # setiap push ke branch main, workflow jalan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/UTSCLOUD
          git pull origin main
          # jika aplikasi membutuhkan restart
          pkill -f app.py  # pastikan nama file app.py sesuai
          nohup python3 app.py &  # menjalankan aplikasi di background
        EOF
